require:
  - rubocop-rails
  - rubocop-faker

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  StyleGuideBaseURL: https://rubystyle.guide

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
